# Generated by Django 4.1.5 on 2023-01-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='standard', max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('engine_type', models.CharField(choices=[('diesel', 'diesel'), ('petrol', 'petrol'), ('electric', 'electric')], default='diesel', max_length=32)),
                ('engine_capacity', models.PositiveSmallIntegerField(help_text='engine capacity in cm³')),
                ('engine_power', models.PositiveSmallIntegerField(help_text='engine power in HP')),
                ('transmission_type', models.CharField(choices=[('manual', 'manual gear'), ('automatic', 'automatic gear')], default='manual', max_length=32)),
                ('seats_no', models.PositiveSmallIntegerField(help_text='number of seats')),
                ('luggage_compartment', models.PositiveSmallIntegerField(help_text='number of bags')),
                ('is_available', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category')),
                ('features', models.ManyToManyField(to='cars.feature')),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
