# Generated by Django 4.1.5 on 2023-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('engine_type', models.CharField(max_length=32)),
                ('engine_capacity', models.CharField(max_length=32)),
                ('engine_power', models.CharField(max_length=32)),
                ('is_available', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
