# Generated by Django 4.1.5 on 2023-01-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_order_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carr',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars/'),
        ),
    ]
