# Generated by Django 4.1.5 on 2023-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_department_car_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
