# Generated by Django 4.1.5 on 2023-01-28 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'managers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_set', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
