# Generated by Django 4.1.5 on 2023-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_department_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carr',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='start_rent',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_rent',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
